version: '3.1'
services:
  db:
    image: mysql
    container_name: cadastro-projetos
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - cadastro-projetos:/var/lib/mysql
volumes:
  cadastro-projetos: